import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {ArchiveAdapter,applyArchiveCorrections} from '../src/archive-adapter.mjs';
const binding={sessionId:'session-a',guildId:'guild-a',channelId:'room-a',startedAtMs:1000,sampleRateHz:48000,channels:1,sampleFormat:'s16le',speakerIds:['alice','bob'],sourceRef:'source-a',retentionPolicyRef:'owner-policy-a'};
function fixture(t,extra={}){const dir=mkdtempSync(path.join(os.tmpdir(),'archive-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));let seals=0,intents=0,media;const config={journalPath:path.join(dir,'queue.sqlite'),authorize:()=>true,sink:{seal:async x=>{seals++;media=x;return {sessionId:x.binding.sessionId,idempotencyKey:x.idempotencyKey,archiveRef:'existing-store/session-a'};}},asr:async({speakerId})=>[{idx:0,start:0,end:0.001,text:speakerId??'mixed',confidence:.8}],correct:async()=>[],recordIntent:async x=>{intents++;return {idempotencyKey:x.idempotencyKey,receiptRef:'intent-receipt'};},...extra};return {config,counts:()=>({seals,intents}),media:()=>media};}
test('shared timeline preserves final sample, silence and mixed overlap through restart',async t=>{const f=fixture(t);let a=new ArchiveAdapter(f.config);a.begin(binding);const pcm=Buffer.alloc(4);pcm.writeInt16LE(100,0);pcm.writeInt16LE(200,2);a.append({sessionId:'session-a',speakerId:'alice',sourceId:'a1',startFrame:48,pcm});a.append({sessionId:'session-a',speakerId:'bob',sourceId:'b1',startFrame:49,pcm:Buffer.from([50,0])});assert.throws(()=>a.seal('session-a',49),/LAST_AUDIO_LOST/);a.seal('session-a',50);a.close();a=new ArchiveAdapter(f.config);await a.processNext();const m=f.media();assert.equal(m.tracks[0].pcm.readInt16LE(0),0);assert.equal(m.tracks[0].pcm.readInt16LE(98),200);assert.equal(m.mixed.readInt16LE(98),250);assert.equal(await a.processNext(),null);a.close();assert.deepEqual(f.counts(),{seals:1,intents:1});});
test('unknown speaker, duplicate conflict, overlap and append after seal are rejected',t=>{const f=fixture(t),a=new ArchiveAdapter(f.config);a.begin(binding);const chunk={sessionId:'session-a',speakerId:'alice',sourceId:'a1',startFrame:0,pcm:Buffer.alloc(96)};assert.throws(()=>a.append({...chunk,speakerId:'unknown'}),/SPEAKER_MISMATCH/);a.append(chunk);assert.equal(a.append(chunk).duplicate,true);assert.throws(()=>a.append({...chunk,startFrame:1}),/REPLAY_CONFLICT/);assert.throws(()=>a.append({...chunk,sourceId:'a2',startFrame:1}),/TIME_OVERLAP/);a.seal('session-a',48);assert.throws(()=>a.append({...chunk,sourceId:'a2',startFrame:48}),/ALREADY_SEALED/);a.close();});
test('failed correction resumes without repeating archive or successful ASR',async t=>{let fail=true,asr=0;const f=fixture(t,{asr:async()=>{asr++;return [{idx:0,start:0,end:.001,text:'raw',confidence:.8}];},correct:async()=>{if(fail)throw Error('provider unavailable');return [];}});let a=new ArchiveAdapter(f.config);a.begin(binding);a.append({sessionId:'session-a',speakerId:'alice',sourceId:'a1',startFrame:0,pcm:Buffer.alloc(96)});a.seal('session-a',48);await assert.rejects(a.processNext(),/unavailable/);a.close();fail=false;a=new ArchiveAdapter(f.config);await a.processNext();a.close();assert.equal(asr,3);assert.deepEqual(f.counts(),{seals:1,intents:1});});
test('retention scope is rechecked before processing',async t=>{let allowed=true;const f=fixture(t,{authorize:()=>allowed}),a=new ArchiveAdapter(f.config);a.begin(binding);a.append({sessionId:'session-a',speakerId:'alice',sourceId:'a1',startFrame:0,pcm:Buffer.alloc(96)});a.seal('session-a',48);allowed=false;await assert.rejects(a.processNext(),/SCOPE_REVOKED/);assert.equal(f.counts().seals,0);a.close();});
test('bounded padding, duration and total retained PCM',t=>{const f=fixture(t,{limits:{maxPcmBytes:128,maxJournalPcmBytes:128,maxFrames:100}}),a=new ArchiveAdapter(f.config);a.begin(binding);const c={sessionId:'session-a',speakerId:'alice',sourceId:'a1',startFrame:0,pcm:Buffer.alloc(96)};a.append(c);assert.throws(()=>a.append({...c,sourceId:'a2',startFrame:48}),/PCM_LIMIT/);assert.throws(()=>a.seal('session-a',48),/PADDED_LIMIT/);assert.throws(()=>a.append({...c,sourceId:'a2',startFrame:100}),/FRAME_INVALID/);a.close();});
test('corrections keep speaker, idx, exact time, raw and explanation',()=>{const raw=[{idx:0,speaker_id:'alice',start:0,end:1,text:'old',confidence:.7,source:'individual'}];const e={idx:0,speaker_id:'alice',start:0,end:1,before:'old',after:'new',reason:'context',confidence:.8};const c=applyArchiveCorrections(raw,[e]);assert.equal(c[0].raw_text,'old');assert.equal(raw[0].text,'old');for(const bad of [{...e,speaker_id:'bob'},{...e,start:.2},{...e,before:'fake'}])assert.throws(()=>applyArchiveCorrections(raw,[bad]),/IDENTITY/);});
