import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,mkdir,symlink} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {Store} from '../src/store.mjs';
import {Pipeline} from '../src/pipeline.mjs';
import {exampleConfig,Config} from '../src/config.mjs';
import {digest,redact,safePath,inside} from '../src/common.mjs';
import {TranscriptTurns} from '../src/transcripts.mjs';
import {pcm48StereoTo24Mono,pcm24MonoTo48Stereo} from '../src/voice-providers.mjs';
import {verifyArtifacts} from '../src/worker.mjs';

const actor='100000000000000002';
const source=(extra={})=>({provider:'discord',guildId:'100000000000000001',channelId:'100000000000000003',sourceId:'message-1',actorId:actor,revision:1,readers:[actor],text:'ことだま、資料を作って',final:true,...extra});
const intent=(extra={})=>({kind:'request',title:'資料作成',request:'資料を作って',action:'write_file',explicit:true,complete:true,acceptance:['本文がある'],...extra});
const analysis=(items=[intent()])=>({summary:'資料作成の依頼',intents:items,replyRequested:false,reply:''});
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'ktdm-template-test-'));const store=new Store(root);t.after(async()=>{store.close();assert(inside(os.tmpdir(),root));assert(path.basename(root).startsWith('ktdm-template-test-'));await rm(root,{recursive:true,force:true});});return {root,store};}

test('defaults keep Live assist, transcribe-only minutes and an explicit zero audio budget',()=>{const c=exampleConfig();assert.equal(c.voice.mode,'assist');assert.equal(c.voice.minutesModel,'gpt-live-transcribe');assert.equal(c.voice.maxDailyAudioSeconds,0);assert.equal(c.voice.storeAudio,false);assert.equal(c.archive?.whisperProtocol??'local','local');});
test('primary models default to Luna in existing settings and preserve explicit overrides',()=>{const old=exampleConfig();delete old.worker.model;old.analyzer={executable:'codex'};const c=Config.parse(old);assert.equal(c.worker.model,'gpt-5.6-luna');assert.equal(c.analyzer.model,'gpt-5.6-luna');assert.equal(c.analyzer.kind,'codex_cli');old.worker.model='chosen-primary';assert.equal(Config.parse(old).worker.model,'chosen-primary');});
test('analyzer context keeps the newest sources inside one total character budget',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.analyzer.maxContextSources=2;config.analyzer.maxContextChars=10;for(let n=0;n<4;n++)store.ingest(source({sourceId:'context-'+n,revision:n+1,text:String(n).repeat(8)}));const p=new Pipeline({store,config,analyzer:{},worker:{}}),context=p.context(source({sourceId:'current'}),actor);assert.equal(context.length,2);assert.equal(context.map(item=>item.text).join('').length,10);assert.equal(context.at(-1).text,'3'.repeat(8));});
test('source correction invalidates a running task and retains original source bytes',async t=>{const {store}=await fixture(t);const first=store.ingest(source());const s=store.source(first.key,actor);const task=store.createTask(s,intent());store.claim(task.id,1);store.ingest(source({revision:2,text:'やっぱり実行しないで'}));assert.equal(store.task(task.id,actor).state,'stale');assert.throws(()=>store.finish(task.id,1,{state:'needs_review'}),/SOURCE_CHANGED/);assert.equal(store.db.prepare('SELECT count(*) AS n FROM source_versions').get().n,2);});
test('source and task replay survive reopening without duplicate work',async t=>{const {root,store}=await fixture(t);const key=store.ingest(source()).key;const first=store.createTask(store.source(key,actor),intent());const second=new Store(root);try{assert.equal(second.ingest(source()).state,'duplicate');assert.equal(second.createTask(second.source(key,actor),intent()).id,first.id);assert.equal(second.tasks(actor).length,1);}finally{second.close();}});
test('reused source revision with changed body or audience is refused',async t=>{const {store}=await fixture(t);store.ingest(source());assert.throws(()=>store.ingest(source({text:'別の指示'})),/SOURCE_REVISION_CONFLICT/);assert.throws(()=>store.ingest(source({readers:[actor,'other']})),/SOURCE_REVISION_CONFLICT/);assert.equal(store.ingest(source({revision:0,text:'old'})).state,'stale');});
test('private source cannot be read or used by another operator',async t=>{const {store}=await fixture(t);const key=store.ingest(source()).key;const task=store.createTask(store.source(key,actor),intent());assert.throws(()=>store.source(key,'other'),/SOURCE_ACCESS_DENIED/);assert.throws(()=>store.task(task.id,'other'),/TASK_ACCESS_DENIED/);assert.equal(store.sources('other').length,0);});
test('a question and a proposal create intents but never execute',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];let calls=0;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis([intent({kind:'question',explicit:false}),intent({kind:'proposal',explicit:false})])},worker:{run:async()=>{calls++;}}});await p.ingest(source({text:'どう思う？'}),{execute:true});await p.tail;assert.equal(store.listIntents(actor).length,2);assert.equal(store.tasks(actor).length,0);assert.equal(calls,0);});
test('a structured voice-end decision closes only the conversation path and suppresses a late spoken reply',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});const actions=[],replies=[];const p=new Pipeline({store,config,analyzer:{analyze:async()=>({...analysis([]),replyRequested:true,reply:'遅い返答',voiceAction:'end_conversation'})},worker:{run:async()=>{}},onVoiceAction:async value=>actions.push(value),onReply:async value=>replies.push(value)});await p.ingest(source({text:'もういいよ',metadata:{kind:'voice',voiceEpoch:3}}),{reply:true});assert.equal(actions.length,1);assert.equal(actions[0].action,'end_conversation');assert.equal(replies.length,0);assert.equal(store.tasks(actor).length,0);});
test('imported instructions, partial speech and non-addressed text cannot execute',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];let calls=0;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis()},worker:{run:async()=>{calls++;}}});await p.ingest(source({provider:'file',sourceId:'file'}),{execute:true});await p.ingest(source({sourceId:'delta',final:false}),{execute:true});await p.ingest(source({sourceId:'unaddressed'}),{execute:false});await p.tail;assert.equal(store.tasks(actor).length,0);assert.equal(calls,0);});
test('explicit request runs once and remains reviewable rather than auto-accepted',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];let calls=0;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis()},worker:{run:async()=>{calls++;return {state:'needs_review',summary:'候補',artifacts:[]};}}});await p.ingest(source(),{execute:true});await p.tail;await p.ingest(source(),{execute:true});await p.tail;assert.equal(calls,1);assert.equal(store.tasks(actor)[0].state,'needs_review');});
test('policy revocation before dispatch prevents worker execution',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];let allowed=true,calls=0;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis()},authorize:async()=>{if(!allowed)throw Error('revoked');allowed=false;},worker:{run:async()=>{calls++;}},onError:()=>{}});await p.ingest(source(),{execute:true});await p.tail;assert.equal(calls,0);});
test('unavailable worker reports failure without an unhandled promise',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis()},worker:{run:async()=>{throw Error('offline');}}});await p.ingest(source(),{execute:true});await p.tail;assert.equal(store.tasks(actor)[0].state,'failed');});
test('unknown result delivery is not blindly replayed',async t=>{const {root,store}=await fixture(t);assert.equal(store.claimDelivery('d','本文'),true);const reopened=new Store(root);try{assert.equal(reopened.claimDelivery('d','本文'),false);assert.throws(()=>reopened.claimDelivery('d','changed'),/DELIVERY_CONFLICT/);}finally{reopened.close();}});
test('audio budget is persisted and refuses extra sessions',async t=>{const {root,store}=await fixture(t);store.reserveAudio(900,1);const reopened=new Store(root);try{assert.throws(()=>reopened.reserveAudio(101,1),/AUDIO_BUDGET_EXHAUSTED/);}finally{reopened.close();}assert.throws(()=>store.reserveAudio(1,0),/AUDIO_BUDGET_REQUIRED/);});
test('credential-key spelling variations are redacted while schema handling is separate',()=>{const result=redact({'access-token':'secret',accessToken:'secret',refresh_token:'secret',nested:{password:'secret'}});assert(!JSON.stringify(result).includes('secret'));});
test('artifact readback rejects changed bytes',async t=>{const {root}=await fixture(t);const p=path.join(root,'result.md');await writeFile(p,'a');const task={state:'needs_review',result:{artifacts:[{path:p,sha256:digest('a')}]}};await verifyArtifacts(task);await writeFile(p,'b');await assert.rejects(verifyArtifacts(task),/ARTIFACT_CHANGED/);});
test('workspace path traversal is refused',async t=>{const {root}=await fixture(t);await assert.rejects(safePath(root,'../secret',{mustExist:false}),/PATH_OUTSIDE_WORKSPACE/);});
test('late transcript revises the same utterance instead of creating a new command',async()=>{const turns=[];const f=new TranscriptTurns({settleMs:2,onTurn:t=>turns.push(t)});const t=f.begin(0);f.fragment({id:'a',text:'作って',startMs:0,endMs:10});f.end(t,100);await new Promise(r=>setTimeout(r,10));f.fragment({id:'b',text:'、ではなく調べて',startMs:20,endMs:80});await f.close();assert.equal(turns.length,2);assert.equal(turns[0].id,turns[1].id);assert(turns[1].revision>turns[0].revision);});
test('audio conversion preserves mono sample value and exact sample counts',()=>{const stereo=Buffer.alloc(8);for(let n=0;n<8;n+=2)stereo.writeInt16LE(1234,n);const mono=pcm48StereoTo24Mono(stereo);assert.equal(mono.length,2);assert.equal(mono.readInt16LE(0),1234);assert.deepEqual(pcm24MonoTo48Stereo(mono),stereo);});
test('two stop requests never promote an unconfirmed stop to cancelled',async t=>{const {store}=await fixture(t);const key=store.ingest(source()).key;const task=store.createTask(store.source(key,actor),intent());store.claim(task.id,1);store.cancel(task.id,actor);store.cancel(task.id,actor);assert.equal(store.task(task.id,actor).state,'stopping');assert.throws(()=>store.resume(task.id,actor),/TASK_CANNOT_RESUME/);store.confirmStop(task.id,actor,false);assert.equal(store.task(task.id,actor).state,'uncertain');});
test('another operator cannot cancel a task by naming it in an inferred correction',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});const other='100000000000000009';config.discord.operators.push(other);config.worker.actions=['write_file'];const key=store.ingest(source()).key;const task=store.createTask(store.source(key,actor),intent());const controller=new AbortController();const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis([intent({targetTaskId:task.id})])},worker:{run:async()=>{}},onError:()=>{}});p.active.set(task.id,{sourceKey:key,controller});await assert.rejects(p.ingest(source({sourceId:'other',actorId:other,readers:[other]}),{execute:true}),/TASK_ACCESS_DENIED/);assert.equal(controller.signal.aborted,false);p.active.clear();});
test('source edits keep one Task identity with a new execution revision',async t=>{const {store}=await fixture(t);const key=store.ingest(source()).key;const first=store.createTask(store.source(key,actor),intent({key:'slot'}));store.ingest(source({revision:2,text:'新しい条件で資料を作って'}));const second=store.createTask(store.source(key,actor),intent({key:'slot',request:'新しい条件'}));assert.equal(second.id,first.id);assert(second.revision>first.revision);assert.equal(second.source_revision,2);assert.equal(store.tasks(actor).length,1);});
test('withdrawn background context invalidates the derived running Task',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['write_file'];store.ingest(source({sourceId:'background',text:'重要な背景情報'}));let started,release;const ready=new Promise(r=>started=r);const wait=new Promise(r=>release=r);let observedSignal;
  const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis()},worker:{run:async(_t,context,{signal})=>{assert(context.some(s=>s.text==='重要な背景情報'));observedSignal=signal;started();await wait;return {state:'needs_review',summary:'old',artifacts:[]};}}});
  await p.ingest(source(),{execute:true});await ready;const taskId=store.tasks(actor)[0].id;await p.ingest(source({sourceId:'background',revision:2,text:'',withdrawn:true}),{execute:false});assert(observedSignal.aborted);release();await p.tail;assert.equal(store.taskInternal(taskId).state,'stale');assert.equal(store.taskInternal(taskId).result,null);assert.equal(store.tasks(actor).length,0);
});
test('restart preserves running and stopping tasks as uncertain',async t=>{const {store}=await fixture(t);const key=store.ingest(source()).key;const task=store.createTask(store.source(key,actor),intent());store.claim(task.id,1);store.cancel(task.id,actor);store.reconcileInterrupted();assert.equal(store.task(task.id,actor).state,'uncertain');});

test('related writes in one message share a candidate without promoting a proposal',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['develop','write_file'];const runs=[];const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis([intent({title:'README',request:'READMEを作成',action:'write_file'}),intent({title:'greeting',request:'greetingを修正',action:'develop'}),intent({kind:'proposal',explicit:false,request:'無関係な提案'})])},worker:{run:async task=>{runs.push(task);return {state:'needs_review',summary:'候補',artifacts:[]};}}});await p.ingest(source(),{execute:true});await p.tail;assert.equal(runs.length,1);assert(runs[0].request.includes('READMEを作成'));assert(runs[0].request.includes('greetingを修正'));assert(!runs[0].request.includes('無関係な提案'));assert.equal(runs[0].intentIds.length,2);assert.equal(store.listIntents(actor).length,3);});

test('a grouped write keeps every required action for current-grant checks',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['develop','write_file'];let runs=0;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis([intent({action:'write_file'}),intent({action:'develop'})])},authorize:async task=>{assert.deepEqual(task.requiredActions,['write_file','develop']);if(task.requiredActions.includes('write_file'))throw Error('current write grant revoked');},worker:{run:async()=>{runs++;}}});await assert.rejects(p.ingest(source(),{execute:true}),/current write grant revoked/);await p.tail;assert.equal(runs,0);});
test('a group corrected to one request retains Task identity and only current intent references',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['develop','write_file'];let batch=true;const p=new Pipeline({store,config,analyzer:{analyze:async()=>analysis(batch?[intent({action:'write_file'}),intent({action:'develop'})]:[intent({action:'write_file'})])},worker:{run:async()=>({state:'needs_review',summary:'候補',artifacts:[]})}});await p.ingest(source(),{execute:true});await p.tail;const first=store.tasks(actor)[0];batch=false;await p.ingest(source({revision:2,text:'READMEだけに訂正'}),{execute:true});await p.tail;const current=store.tasks(actor)[0];assert.equal(first.id,current.id);assert.equal(current.intentIds.length,1);assert(current.intentIds.every(id=>store.listIntents(actor).some(i=>i.id===id)));assert.deepEqual(current.requiredActions,['write_file']);});

test('replayed direct command cannot change its operation or current Intent',async t=>{const {store,root}=await fixture(t);const config=exampleConfig({workspace:root});config.worker.actions=['research','develop'];const p=new Pipeline({store,config,analyzer:{},worker:{run:async()=>({state:'needs_review',summary:'候補',artifacts:[]})}});await p.request(source(),{title:'同じ本文',request:'同じ本文',action:'research'});await p.tail;await assert.rejects(p.request(source(),{title:'同じ本文',request:'同じ本文',action:'develop'}),/SOURCE_REVISION_CONFLICT/);assert.equal(store.tasks(actor)[0].action,'research');assert.equal(store.listIntents(actor)[0].action,'research');});

test('a one-time audio allowance cannot be renewed by restart or UTC date rollover',async t=>{const {root,store}=await fixture(t);store.reserveAudio(1500,2,'2026-01-01',2);const next=new Store(root);try{next.reserveAudio(500,2,'2026-01-02',2);assert.throws(()=>next.reserveAudio(1,2,'2026-01-03',2),/AUDIO_TOTAL_BUDGET_EXHAUSTED/);}finally{next.close();}});
