import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {invokeCodex,modelExecution,parseModelJson} from '../src/llm.mjs';
import {check} from '../src/common.mjs';
test('a complete JSON fence is decoded without repairing prose or inferring content',()=>{assert.deepEqual(parseModelJson('```json\n{"summary":"候補","files":[]}\n```'),{summary:'候補',files:[]});assert.throws(()=>parseModelJson('Here is a result:\n```json\n{}\n```'),/MODEL_JSON_INVALID/);assert.throws(()=>parseModelJson('作成しました'),/MODEL_JSON_INVALID/);});
async function fixture(t){const cwd=await mkdtemp(path.join(os.tmpdir(),'ktdm-fallback-'));t.after(async()=>{assert(path.basename(cwd).startsWith('ktdm-fallback-'));await rm(cwd,{recursive:true,force:true});});const failed=path.join(cwd,'failed.mjs'),good=path.join(cwd,'good.mjs');await writeFile(failed,"process.stderr.write('Not logged in. Please run codex login.');process.exit(1);",'utf8');await writeFile(good,"console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:JSON.stringify({summary:'fallback result',files:[]})}}));",'utf8');return {cwd,failed,good,options:{cwd,dataDir:cwd,prompt:'fixture',schema:{type:'object'},sandbox:'read-only'},config:{executable:process.execPath,args:[failed],model:'primary-fixture',timeoutSeconds:5,fallback:{executable:process.execPath,args:[good],model:'fallback-fixture',timeoutSeconds:5}}};}
test('pre-execution auth failure may use the configured fallback and records actual invocation',async t=>{const {config,options}=await fixture(t);const value=await invokeCodex(config,options);assert.equal(value.summary,'fallback result');assert.deepEqual(modelExecution(value),{model:'fallback-fixture',adapter:'codex_cli',fallback:true,primaryModel:'primary-fixture',primaryFailure:'CODEX_LOGIN_REQUIRED'});});
test('fallback never runs after stop or an unsafe write candidate',async t=>{const {config,options}=await fixture(t);const c=new AbortController();c.abort();await assert.rejects(invokeCodex(config,{...options,signal:c.signal}),/CANCELLED/);await assert.rejects(invokeCodex(config,{...options,sandbox:'workspace-write',beforeFallback:async()=>check(false,'FALLBACK_WORKSPACE_CHANGED')}),/FALLBACK_WORKSPACE_CHANGED/);});
test('an ordinary model failure does not silently change the model',async t=>{const {config,options,failed}=await fixture(t);await writeFile(failed,"process.stderr.write('invalid schema');process.exit(1);",'utf8');await assert.rejects(invokeCodex(config,options),/MODEL_COMMAND_FAILED/);});
test('explicit usage limit uses configured fallback only before a write',async t=>{const {config,options,failed}=await fixture(t);await writeFile(failed,"console.log(JSON.stringify({type:'error',message:\"You've hit your usage limit\"}));process.exit(1);",'utf8');const result=await invokeCodex(config,options);assert.equal(modelExecution(result).primaryFailure,'MODEL_USAGE_LIMIT');await assert.rejects(invokeCodex(config,{...options,sandbox:'workspace-write',beforeFallback:async()=>check(false,'FALLBACK_WORKSPACE_CHANGED')}),/FALLBACK_WORKSPACE_CHANGED/);});
