import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyInstallation,invitation} from '../tools/discord-setup.mjs';
import {codexFailure} from '../src/llm.mjs';
const applicationId='100000000000000001',guildId='100000000000000002';
function mock(routes,calls=[]){return async(url,options)=>{assert.equal(options.redirect,'error');calls.push(new URL(url).pathname);const value=routes[calls.at(-1)];assert.ok(value);return {status:value[0],ok:value[0]===200,json:async()=>value[1]};};}
const identity={'/api/v10/oauth2/applications/@me':[200,{id:applicationId,flags:524288}],'/api/v10/users/@me':[200,{id:applicationId,bot:true}]};
test('expired Codex auth becomes a human login instruction without echoing provider diagnostics',()=>{assert.equal(codexFailure({stderr:'Your access token could not be refreshed. Please log out and sign in again.'}),'CODEX_LOGIN_REQUIRED');assert.equal(codexFailure({stderr:'network offline'}),'MODEL_COMMAND_FAILED');});
test('setup separates verified new app credentials from human guild authorization',async()=>{const value=await verifyInstallation({applicationId,guildId,token:'fixture',fetcher:mock({...identity,[`/api/v10/guilds/${guildId}`]:[404]})});assert.equal(value.ok,false);assert.equal(value.applicationVerified,true);assert.equal(value.guildVerified,false);assert.equal(value.humanRequired,true);assert.equal(value.stage,'guild_authorization');assert.equal(JSON.stringify(value).includes('fixture'),false);});
test('setup refuses the old Bot before querying or acting on a guild',async()=>{const calls=[];await assert.rejects(verifyInstallation({applicationId,guildId,token:'fixture',fetcher:mock({'/api/v10/oauth2/applications/@me':[200,{id:'100000000000000009'}]},calls)}),/BOT_APPLICATION_MISMATCH/);assert.equal(calls.length,1);});
test('read-only provider verification never implies post or voice success',async()=>{const value=await verifyInstallation({applicationId,guildId,token:'fixture',fetcher:mock({...identity,[`/api/v10/guilds/${guildId}`]:[200,{id:guildId}],[`/api/v10/guilds/${guildId}/channels`]:[200,[]]})});assert.equal(value.ok,true);assert.equal(value.posted,false);assert.equal(value.voiceConnected,false);const url=new URL(invitation(applicationId,guildId));assert.equal(BigInt(url.searchParams.get('permissions'))&8n,0n);assert.equal(url.searchParams.get('disable_guild_select'),'true');});
